[book]
title = "einfachIOTA Magazines"
authors = ["huhn511"]
language = "en"
multilingual = false
src = "src"

default-theme = "einfachIOTA"
additional-css = ["theme/custom/custom.css"]

[output.html]
theme = "src/theme"